redis:
  command:
    timeoutSeconds: ${REDIS_COMMAND_TIMEOUT_SECONDS:10}
  sentinel:
    enable: ${REDIS_SENTINEL_ENABLE:false}
    list: ${REDIS_SENTINEL_LIST:localhost:26379}
    master: ${REDIS_SENTINEL_MASTER:mymaster}
    p: ${REDIS_SENTINEL_P:123456}
  standalone:
    enable: ${REDIS_STANDALONE_ENABLE:true}
    host: ${REDIS_STANDALONE_HOST:localhost}
    port: ${REDIS_STANDALONE_PORT:6379}
    p: ${REDIS_STANDALONE_P:123456}