spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    datasource-class-name: org.postgresql.ds.PGSimpleDataSource
    username: usr
    password: pass
    hikari:
      pool-name: db-default-db-pool
      auto-commit: false
      maximum-pool-size: 16
      minimum-idle: 3
      connectionTimeout: 10000
      idle-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection.provider_disables_autocommit: true
        jdbc:
          batch_size: 30
    dialect: org.hibernate.dialect.PostgreSQL94Dialect