
server:
  port: 9098
spring:
  threads.virtual.enabled: true
  profiles.include: reactor, redis, postgresql

logging:
  level:
    root: ERROR
    com.example: INFO

application:
  scheduler.cron: "* * 2 * * *"