
server:
  port: 9098
spring:
  threads.virtual.enabled: true
  profiles.include: reactor, redis, postgresql

logging:
  level:
    root: ERROR
    com.example: INFO

topic-gc:
  default-consumer-props:
    fetch-max-bytes: "20971520"
    max-partition-fetch-bytes: "20971520"
  admin-client:
    default-api-timeout: 20000
    request-timeout: 20000
  clusters:
    - name: confluent
      bootstrap-servers: staging-confluent-broker-01-earth.trendyol.com:9092,staging-confluent-broker-02-earth.trendyol.com:9092,staging-confluent-broker-03-earth.trendyol.com:9092,staging-confluent-broker-04-earth.trendyol.com:9092,staging-confluent-broker-05-earth.trendyol.com:9092,staging-confluent-broker-06-earth.trendyol.com:9092,staging-confluent-broker-07-earth.trendyol.com:9092,staging-confluent-broker-08-earth.trendyol.com:9092
    - name: local
      bootstrap-servers: localhost:9092
  scheduler-cron: "* * */3 * * *"