
server:
  port: 9098
spring:
  threads.virtual.enabled: true
  profiles.include: reactor, redis, postgresql

logging:
  level:
    root: ERROR
    com.example: INFO

application:
  scheduler.cron: "* * 2 * * *"

clusters: localhost:9092

topic-gc:
  default-consumer-props:
    fetch-max-bytes: "20971520"
    max-partition-fetch-bytes: "20971520"
  admin-client:
    default-api-timeout: 20000
    request-timeout: 20000